### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by willfaught** [jacamera/disable-youtube-watch-later-autoplay#1]
Installed today. Next video in water later list autoplays when right-clicking on water later link and opening in new tab, and also when clicking directly on a water later link.

**Comment by jacamera** [comment]
@willfaught Can you let me know which OS and browser you're using? Also can you confirm that you reloaded youtube.com or opened a new tab after installing the extension?

**Comment by willfaught** [comment]
Sorry, didn't realize it supported more than Chrome. Chrome v 107.0.5304.87 (Official Build) (x86_64), macOS 13.0 (22A380)

Yes, I tried navigating to new YouTube pages by left-clicking and right-clicking (open in new tab) links in the Watch Later playlist.

**Comment by jacamera** [comment]
@willfaught Sorry for the delayed response but I just tested on Chrome on my Mac and everything appears to be working OK. We might be opted into different youtube.com experiences though so I want to make sure that the extension is running and that the handlers are firing.

I would appreciate if you could perform the following debugging steps to help isolate the problem:

1. Go to your Watch Later list on youtube.com.
2. Press F12 to open the Chrome Developer Console.
3. Select the Sources tab, then the Content Scripts tab, open the Disable Youtube Watch Later Playlist extension content.js file, and set a breakpoint on line 51 by clicking on the line number. (see 1st screenshot)
4. Click on a video title from your Watch Later list.

The click should be intercepted and the playlist parameters removed from the URL (see 2nd screenshot). If any of the steps fail let me know. Please provide screenshots if there are any discrepancies.

<img width="1440" alt="Screen Shot 2022-11-14 at 16 45 22" src="https://user-images.githubusercontent.com/18013188/201776306-5e4f1f7d-a4f1-4ec9-95c5-136ef37b9fad.png">

<img width="1440" alt="Screen Shot 2022-11-14 at 16 46 36" src="https://user-images.githubusercontent.com/18013188/201776322-16aa2f09-f8f1-48fd-bb74-c19d606867dc.png">

**Comment by willfaught** [comment]
Thanks for the detailed steps. When I tried it again, it worked, both with and without the breakpoint. Not sure why. I'll close this. Thanks for your time.
