### ISSUE TITLE
Not working in LibreWolf 107 with Debian 11

### ISSUE THREAD

**Issue by Chirunos** [jacamera/disable-youtube-watch-later-autoplay#2]
Extension version: 1.0.2

**Comment by jacamera** [comment]
There's no reason I can think of why this shouldn't work in LibreWolf. Before I try to replicate your environment, can you please just verify that the extension's content script is running on the YouTube page? And can you also please verify that you've tried opening a new youtube.com tab after installing the extension? Unfortunately when the extension is first installed it won't work on any existing youtube.com tabs, only new ones.

To verify that the script is running:
- Go to the YouTube Watch Later list at https://www.youtube.com/playlist?list=WL in a new tab.
- Right-click and select "Inspect" to open the Developer Tools. (Should be the same or similar in LibreWolf compared to FireFox).
- Select the "Debugger" tab and verify that "Disable YouTube Watch Later Autoplay" is listed under "Sources" (see screenshot below).
- Try clicking on a link to a video and see if the `list` and `index` parameters are not removed from the URL to disable the autoplay behavior.

![image](https://user-images.githubusercontent.com/18013188/204955500-03e4d982-ed17-4079-8358-241b6d87de54.png)

**Comment by Chirunos** [comment]
> There's no reason I can think of why this shouldn't work in LibreWolf. Before I try to replicate your environment, can you please just verify that the extension's content script is running on the YouTube page? And can you also please verify that you've tried opening a new youtube.com tab after installing the extension? Unfortunately when the extension is first installed it won't work on any existing youtube.com tabs, only new ones.
> 
> To verify that the script is running:
> 
>     * Go to the YouTube Watch Later list at https://www.youtube.com/playlist?list=WL in a new tab.
> 
>     * Right-click and select "Inspect" to open the Developer Tools. (Should be the same or similar in LibreWolf compared to FireFox).
> 
>     * Select the "Debugger" tab and verify that "Disable YouTube Watch Later Autoplay" is listed under "Sources" (see screenshot below).
> 
>     * Try clicking on a link to a video and see if the `list` and `index` parameters are not removed from the URL to disable the autoplay behavior.
> 
> 
> ![image](https://user-images.githubusercontent.com/18013188/204955500-03e4d982-ed17-4079-8358-241b6d87de54.png)

Sorry, my environment changed, I'm now on Firefox Nightly and this screenshot was on Windows 10, no extensions are a source
![image](https://user-images.githubusercontent.com/85644671/225707722-fcb26f49-1713-42b2-9fc3-29e0376e8f64.png)

**Comment by jacamera** [comment]
Thank you for the update and the screenshot. I'm currently using Windows 10 as well so I just installed Firefox Nightly but the extension is working fine for me there.

I'm not sure why the resources in your debugger window are different than the ones that I am seeing. Can you send another screenshot that shows the top of the window including the title bar like the one that I shared?

Also, as another debugging step, can you go to your Watch Later list and copy and paste a link to one of the videos? It should look something like this by default:
- https://www.youtube.com/watch?v=TgYOxyr1w-w&list=WL&index=5&pp=gAQBiAQB

Or with the `list` and `index` parameters removed if the extension is working as intended:
- https://www.youtube.com/watch?v=TgYOxyr1w-w&pp=gAQBiAQB

**Comment by Chirunos** [comment]
> Thank you for the update and the screenshot. I'm currently using Windows 10 as well so I just installed Firefox Nightly but the extension is working fine for me there.
> 
> I'm not sure why the resources in your debugger window are different than the ones that I am seeing. Can you send another screenshot that shows the top of the window including the title bar like the one that I shared?
> 
> Also, as another debugging step, can you go to your Watch Later list and copy and paste a link to one of the videos? It should look something like this by default:
> 
>     * https://www.youtube.com/watch?v=TgYOxyr1w-w&list=WL&index=5&pp=gAQBiAQB
> 
> 
> Or with the `list` and `index` parameters removed if the extension is working as intended:
> 
>     * https://www.youtube.com/watch?v=TgYOxyr1w-w&pp=gAQBiAQB

Now, when I go to my Watch Later playlist and choose a video, it redirects me to the page without the Watch Later URL queries. I just want to make sure this is the intended behavior, after I saw the screenshots on AMO again. If this is the intended behavior, feel free to close this issue.

What I expected this extension to do was:
- when I choose a video, the Watch Later is still shown in the video's page (`&list` and `&index` queries are still present) playlist somewhere in the page;
- when the video ends, it gets paused (next video on the playlist doesn't auto-play).

**Comment by jacamera** [comment]
Great, I'm glad it's working now. What you described is indeed the intended behavior. I tried to highlight that in the screenshots and description but both could definitely use some improvement.

Your idea of pausing the video at the end is very interesting and is something I hadn't thought of before. It seems like it would be pretty straight forward to set up a mutation observer to monitor the playback time and then trigger a click on the pause button at the last second. Might be a little tricky to reliably hook into the player after in-page navigation but maybe not be too bad.

Either way, thanks for the idea and feedback! There's already around 400 users from the Chrome store and the URL query param method works and is simple so I'll probably leave it as-is for now. Definitely something to consider and play around with though for future versions. There could even be an option to choose which kind of method is used.
